### ISSUE TITLE
java.lang.Integer cannot be cast to com.mongodb.DBObject

### ISSUE THREAD

**Issue by dvohra** [leonlee/flume-ng-mongodb-sink#2]
The flume-ng-mongodb-sink generates the following exception when used with https://github.com/keedio/flume-ng-sql-source

java.lang.ClassCastException: java.lang.Integer cannot be cast to com.mongodb.DBObject

**Comment by clevertension** [comment]
You should enable the json wrapper such as 

```
agent2.sinks.sink2.autoWrap = true
```

**Comment by dvohra** [comment]
Setting 
agent2.sinks.sink2.autoWrap = true
 fixed the issue. Thanks.
